/**
 * Codegen: turns a trained `model.json` into the shipped weights module,
 * `src/engine/kernels/onset-head-weights.ts`, plus the adjacent provenance
 * JSON (comment-free, so the record survives without violating the
 * no-identifiers rule).
 *
 * The weights travel as base64 of the raw little-endian float32 bytes rather
 * than as 19,833 numeric literals: the decode is exact (bit-for-bit, which is
 * what lets the parity test pin the trainer's logits to 1e-5), the module
 * stays a fraction of the size, and the decoder is twenty lines of plain
 * TypeScript with no globals — `atob` is a DOM global and `Buffer` is Node,
 * and `src/engine/**` may use neither.
 *
 * Usage:  bun training/export-weights.ts [--model training/out/model] [--data <guitarset-root>]
 */

import { createHash } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { PARAM_COUNT } from "./model.js";

function arg(name: string, fallback: string): string {
  const i = process.argv.indexOf(`--${name}`);
  return i >= 0 && i + 1 < process.argv.length ? (process.argv[i + 1] as string) : fallback;
}

const modelDir = arg("model", "training/out/model");
const dataRoot = arg("data", "/home/user/datasets/guitarset");

const model = JSON.parse(readFileSync(join(modelDir, "model.json"), "utf8")) as {
  paramCount: number;
  params: number[];
  seed: number;
  lr: number;
  batchSize: number;
  scalarMode: string;
  valPlayers: string[];
  bestEpoch: number;
  valAuc: number;
};
if (model.paramCount !== PARAM_COUNT || model.params.length !== PARAM_COUNT) {
  throw new Error(`model.json param count ${model.params.length} != expected ${PARAM_COUNT}`);
}

const params = Float32Array.from(model.params);
const bytes = new Uint8Array(params.length * 4);
const view = new DataView(bytes.buffer);
for (let i = 0; i < params.length; i++) view.setFloat32(i * 4, params[i] as number, true);
const b64 = Buffer.from(bytes).toString("base64");
const weightsHash = createHash("sha256").update(bytes).digest("hex");

const lines: string[] = [];
lines.push("/**");
lines.push(" * Generated by `training/export-weights.ts` — do not edit by hand.");
lines.push(" *");
lines.push(" * The onset head's trained parameters: raw little-endian float32 bytes,");
lines.push(" * base64-encoded, decoded once at module load by the plain decoder below.");
lines.push(" * Retraining and re-exporting is the only supported way to change them;");
lines.push(" * provenance (dataset manifest, split, training run) lives in the adjacent");
lines.push(" * `onset-head-weights.provenance.json`, and the layout is owned by");
lines.push(" * `onset-head.ts`. Part of `src/engine/` — no DOM, no globals, no npm");
lines.push(" * imports, which is why the decoder is here instead of `atob`.");
lines.push(" */");
lines.push("");
lines.push(`export const ONSET_HEAD_PARAM_COUNT = ${PARAM_COUNT};`);
lines.push("");
lines.push(`const WEIGHTS_BASE64 =`);
for (let i = 0; i < b64.length; i += 96) {
  const chunk = b64.slice(i, i + 96);
  lines.push(`  "${chunk}"${i + 96 < b64.length ? " +" : ";"}`);
}
lines.push("");
lines.push(`const B64_ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";`);
lines.push("");
lines.push("function decode(base64: string, floats: number): Float32Array {");
lines.push("  const lookup = new Int16Array(128).fill(-1);");
lines.push("  for (let i = 0; i < B64_ALPHABET.length; i++) lookup[B64_ALPHABET.charCodeAt(i)] = i;");
lines.push("  const bytes = new Uint8Array(floats * 4);");
lines.push("  let bits = 0;");
lines.push("  let bitCount = 0;");
lines.push("  let out = 0;");
lines.push("  for (let i = 0; i < base64.length; i++) {");
lines.push("    const v = lookup[base64.charCodeAt(i)] ?? -1;");
lines.push("    if (v < 0) continue;");
lines.push("    bits = (bits << 6) | v;");
lines.push("    bitCount += 6;");
lines.push("    if (bitCount >= 8) {");
lines.push("      bitCount -= 8;");
lines.push("      bytes[out++] = (bits >> bitCount) & 0xff;");
lines.push("    }");
lines.push("  }");
lines.push("  if (out !== bytes.length) {");
lines.push("    throw new Error(`onset head weights: decoded ${out} bytes, expected ${bytes.length}`);");
lines.push("  }");
lines.push("  const view = new DataView(bytes.buffer);");
lines.push("  const params = new Float32Array(floats);");
lines.push("  for (let i = 0; i < floats; i++) params[i] = view.getFloat32(i * 4, true);");
lines.push("  return params;");
lines.push("}");
lines.push("");
lines.push("export const ONSET_HEAD_PARAMS: Float32Array = decode(WEIGHTS_BASE64, ONSET_HEAD_PARAM_COUNT);");
lines.push("");

const outTs = "src/engine/kernels/onset-head-weights.ts";
writeFileSync(outTs, lines.join("\n"));

const manifest: Record<string, unknown> = {
  weightsSha256: weightsHash,
  paramCount: PARAM_COUNT,
  architecture:
    "patch 9x60 -> conv3x3x8/relu -> maxpool(f,2) -> conv3x3x16/relu -> maxpool(f,3) -> dense24/relu; scalars 16 -> dense16/relu; concat -> dense24/relu -> dense1 -> sigmoid",
  inputs:
    "whitened log-band patch (m=0.99 floor=0.01, 60 bands 65-8000Hz, 9 hops ending at the decision hop, engine hop grid); 12 rearticulation witnesses; 4 whitened flux readings; fixed log1p transforms per onset-head.ts",
  training: {
    dataset: "GuitarSet (Zenodo record 3371780), annotation + audio_mono-mic + audio_mono-pickup_mix, resampled to 48kHz mono",
    flavors: ["mic", "pickup"],
    chains: ["clean", "amp", "room"],
    labelRule:
      "engine rearticulation trace events; positive iff a merged (30ms) note_midi onset lies within 70ms and no Note opened earlier in trace order covers it",
    split: `grouped by player; validation players ${model.valPlayers.join(",")}`,
    scalarMode: model.scalarMode,
    seed: model.seed,
    lr: model.lr,
    batchSize: model.batchSize,
    bestEpoch: model.bestEpoch,
    externalValAuc: Number(model.valAuc.toFixed(4)),
  },
};
for (const archive of ["annotation.zip", "audio_mono-mic.zip", "audio_mono-pickup_mix.zip"]) {
  const p = join(dataRoot, archive);
  if (existsSync(p)) {
    (manifest as { datasetSha256?: Record<string, string> }).datasetSha256 ??= {};
    (manifest.datasetSha256 as Record<string, string>)[archive] = createHash("sha256")
      .update(readFileSync(p))
      .digest("hex");
  }
}
writeFileSync(
  "src/engine/kernels/onset-head-weights.provenance.json",
  JSON.stringify(manifest, null, 2) + "\n"
);

// The parity references travel with the tests, so the pinned logits survive
// into any checkout without the training outputs.
const references = readFileSync(join(modelDir, "references.json"), "utf8");
writeFileSync("tests/engine/onset-head-references.json", references);

console.log(`wrote ${outTs} (${(lines.join("\n").length / 1024).toFixed(0)}KB), provenance JSON, test references`);
console.log(`weights sha256 ${weightsHash}`);
